title: "AE-Cases"
description: "AE-Cases is a collection of cases for the AE Modular format synth modules."
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false